title: Mike McBride
email: mmcbride1007@gmail.com
description: Personal resume of Mike McBride
baseurl: "/resume"
url: "https://mikemcbride.github.io"
website: "https://mikemcbride.me"

# Build settings
markdown: kramdown